### ISSUE TITLE
Fix css specificity for content class

### ISSUE THREAD

**Issue by RickCogley** [RickCogley/RCC-Hugo2015#6]
Css entry for ".content" is conflicting with nanoGallery's class, and causing nanoGallery to zoom photos only into the main content area, rather than full screen as expected. Not specific enough:

``` css
.content {
padding: 2rem 3rem 0;
margin-left: 25%;
}
```

Per https://github.com/Kris-B/nanoGALLERY/issues/77#issuecomment-107638081

THanks @Kris-B :-)
